spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cinema?characterEncoding=UTF-8
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
