spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cinema
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
