spring:
  datasource:
    url: jdbc:h2:mem:testdb  # ✅ H2 인메모리 데이터베이스 사용
    driver-class-name: org.h2.Driver  # ✅ H2 드라이버 지정
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
