services:
  db:
    image: mysql:latest
    container_name: redis-study-mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=testdb
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d