version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cinema_db
    ports:
      - "3306:3306"
    volumes:
      - cinema_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'cinema'
      MYSQL_DATABASE: cinema_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - cinema_network

  redis:
    container_name: cinema_redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - cinema_redis_data:/data
    networks:
      - cinema_network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cinema_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cinema_kafka
    depends_on:
      - cinema_zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cinema_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cinema_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  cinema_mysql_data:
  cinema_redis_data:

networks:
  cinema_network: