spring:
  profiles:
    active: application
  application:
    name: cinema
  datasource:
    url: jdbc:mysql://localhost:33306/cinema?useUnicode=true&character_set_server=utf8mb4&collation=utf8mb4_general_ci
    username: user
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
