spring.application.name: movie-api
spring.profiles.active: local

spring:
  config:
    import:
      - movie-db.yml
  web.resources.add-mappings: false

  messages:
    encoding: UTF-8  # 메시지 인코딩 설정 (한글 깨짐 방지)

    mvc:
      locale: ko_KR  # 기본 로케일을 한국어로 설정
      locale-resolver: fixed  # 로케일을 고정 (한글 적용)

  http.encoding:
    charset: UTF-8
    enabled: true
    force: true  # 모든 요청과 응답을 UTF-8로 강제 적용


server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---

spring.config.activate.on-profile: local

