spring:
  application:
    name: hanghae-cinema
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?characterEncoding=UTF-8
    username: root
    password: cinema
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always  # 애플리케이션 시작 시 SQL 스크립트 실행
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true  # SQL 로깅 시 포맷팅
        use_sql_comments: true  # SQL 주석 표시
    defer-datasource-initialization: true  # JPA 초기화 후 SQL 실행