version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: redis_2nd_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redis_2nd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    external: false
