server:
  port: 8080

spring:
  application:
    name: movie

  datasource:
    url: jdbc:mysql://localhost:3305/movie
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      platform: mysql
      data-locations: classpath:data.sql